# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-21 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Job', max_length=50)),
                ('input_filename', models.CharField(help_text='Input File', max_length=255)),
                ('input_path', models.CharField(help_text='Input Path', max_length=255)),
                ('basename', models.CharField(help_text='Destination Basename', max_length=100)),
                ('output_path', models.CharField(help_text='Destination Path', max_length=255)),
                ('priority', models.CharField(default='5', help_text='0: Max priority, 9: Min Priority', max_length=1)),
                ('job_id', models.IntegerField(blank=True, help_text='Transcoder job ID')),
                ('status', models.CharField(choices=[('Q', 'Queued'), ('P', 'Processing'), ('D', 'Done'), ('E', 'Error')], default='D', help_text='Job Status', max_length=1)),
                ('progress', models.IntegerField(default=0, help_text='Job Progress')),
                ('speed', models.CharField(blank=True, max_length=10)),
                ('message', models.CharField(blank=True, help_text='Error or Warning message', max_length=510)),
            ],
        ),
        migrations.CreateModel(
            name='Preset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Preset', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transcoder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Transcoder', max_length=50, unique=True)),
                ('ip', models.CharField(help_text='IP of the Transcoder', max_length=15)),
                ('port', models.IntegerField(help_text='Port of the Transcoder', max_length=5)),
                ('slots', models.IntegerField(help_text='Availables slots', max_length=3)),
                ('enabled', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='preset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elmcafiolo.Preset'),
        ),
        migrations.AddField(
            model_name='job',
            name='transcoder',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='elmcafiolo.Transcoder'),
        ),
    ]
