# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-21 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elmcafiolo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcoder',
            name='port',
            field=models.IntegerField(help_text='Port of the Transcoder'),
        ),
        migrations.AlterField(
            model_name='transcoder',
            name='slots',
            field=models.IntegerField(help_text='Availables slots'),
        ),
    ]
