# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-21 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elmcafiolo', '0002_auto_20160421_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcoder',
            name='slots',
            field=models.IntegerField(blank=True, help_text='Availables slots'),
        ),
    ]
