# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-21 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elmcafiolo', '0003_auto_20160421_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='transcoder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elmcafiolo.Transcoder'),
        ),
    ]
