# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-22 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elmcafiolo', '0007_auto_20160422_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcoder',
            name='message',
            field=models.CharField(blank=True, help_text='Error or Warning message', max_length=510),
        ),
        migrations.AddField(
            model_name='transcoder',
            name='preset_master',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
