# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the format', max_length=50)),
                ('extension', models.CharField(help_text='Extension of the result file', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='H264Preset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Preset', max_length=50)),
                ('suffix', models.CharField(help_text='Text between basename and extension', max_length=50)),
                ('video_codec', models.CharField(choices=[('libx264', 'libx264')], help_text='Video Library', max_length=20)),
                ('resolution', models.CharField(help_text='Video Resolution: WxH', max_length=20)),
                ('framerate', models.CharField(help_text='Video Frame Rate', max_length=5)),
                ('video_bitrate', models.CharField(help_text='Video Bit Rate expressed in Kbps', max_length=50)),
                ('buffer_size', models.CharField(help_text='Video Buffer Size expressed in Kbps', max_length=50)),
                ('gop_size', models.CharField(help_text='GOP Size', max_length=50)),
                ('reference_frames', models.CharField(help_text='Number of Referense Frames', max_length=50)),
                ('crf', models.CharField(default='18', help_text='Constant Rate Factor: 0 Better, 50 worst', max_length=2)),
                ('profile', models.CharField(choices=[('baseline', 'baseline'), ('main', 'main'), ('high', 'high'), ('high10', 'high10'), ('high422', 'high422'), ('high444', 'high444')], help_text='H264 Profiles', max_length=20)),
                ('level', models.CharField(choices=[('3.0', '3.0'), ('3.1', '3.1'), ('4.0', '4.0'), ('4.1', '4.1'), ('4.2', '4.2')], help_text='H264 Levels', max_length=20)),
                ('audio_codec', models.CharField(choices=[('libfdk_aac', 'libfdk_aac')], help_text='Audio Library', max_length=20)),
                ('audio_bitrate', models.CharField(help_text='Audio Bit Rate expressed in Kbps', max_length=20)),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elemento.Format')),
            ],
        ),
        migrations.CreateModel(
            name='HLSPreset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Preset', max_length=50)),
                ('segment_time', models.CharField(help_text='Segment time expressed in seconds', max_length=6)),
                ('extension', models.CharField(default='m3u8', help_text='Playlist Extension', max_length=5)),
                ('h264_presets', models.ManyToManyField(to='elemento.H264Preset')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the format', max_length=50)),
            ],
        ),
    ]
