# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elemento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable', models.BooleanField()),
                ('date', models.DateField(auto_now_add=True)),
                ('workers', models.CharField(help_text='Max number of simultaneous Workers', max_length=2)),
                ('temporal_path', models.CharField(help_text='Path to temporal destination Files', max_length=255)),
                ('delete_on_success', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], help_text='Automatic delete after transcode', max_length=1)),
            ],
        ),
    ]
