# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elemento', '0002_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='ffmpeg_bin',
            field=models.CharField(default='ffmpeg', help_text='ffmpeg executable', max_length=255),
            preserve_default=False,
        ),
    ]
