# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 03:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elemento', '0003_config_ffmpeg_bin'),
    ]

    operations = [
        migrations.CreateModel(
            name='OuputFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('filename', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(help_text='Name of the Job', max_length=50),
        ),
        migrations.AddField(
            model_name='ouputfile',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elemento.Job'),
        ),
    ]
