# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elemento', '0004_auto_20160217_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='hls_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='elemento.HLSPreset'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='input_filename',
            field=models.CharField(default='a', help_text='Input File', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='input_path',
            field=models.CharField(default='a', help_text='Input Path', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='message',
            field=models.CharField(blank=True, help_text='Error or Warning message', max_length=510),
        ),
        migrations.AddField(
            model_name='job',
            name='priority',
            field=models.CharField(default='9', help_text='0: Max priority, 9 Min Priority', max_length=1),
        ),
        migrations.AddField(
            model_name='job',
            name='progress',
            field=models.CharField(blank=True, help_text='Job Progress', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('Q', 'Queued'), ('P', 'Processing'), ('D', 'Done'), ('E', 'Error')], default='D', help_text='Job Status', max_length=1),
        ),
    ]
